name: TachyonRefreshed
version: '1.0'
main: es.redactado.tachyonRefreshed.TachyonLibrary
api-version: '1.21'
description: A high-performance schematic library using PacketEvents and Guice
author: Redactado
website: https://github.com/redactado/Tachyon-paper